# Generated by Django 3.2 on 2025-02-15 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', models.JSONField()),
                ('range_start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('range_end', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='BulkCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bulkcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience')], max_length=50)),
                ('info', models.JSONField(blank=True, default={}, null=True)),
                ('rest_id', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('rest_id', 'service')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience')], default='instagram', max_length=50)),
                ('code', models.CharField(max_length=500, unique=True)),
                ('info', models.JSONField(default={})),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('info', models.JSONField(default={}, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('request_record_type', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=255)),
                ('data_point', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('r_type', models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('put', 'PUT'), ('delete', 'DELETE')], max_length=10)),
                ('bot_username', models.CharField(blank=True, max_length=100)),
                ('logged_in', models.BooleanField(default=False)),
                ('params', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('data_text', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField()),
                ('Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_text', to='core.profile')),
                ('tasks', models.ManyToManyField(to='core.Task')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(to='core.Task'),
        ),
        migrations.CreateModel(
            name='PostText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='core.post')),
                ('tasks', models.ManyToManyField(to='core.Task')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.post')),
                ('tasks', models.ManyToManyField(to='core.Task')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='tasks',
            field=models.ManyToManyField(to='core.Task'),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=36, unique=True)),
                ('run_id', models.CharField(editable=False, max_length=36, unique=True)),
                ('block_name', models.CharField(blank=True, max_length=500, null=True)),
                ('output_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_by', models.ManyToManyField(to='core.Task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('bot_username', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.CharField(max_length=50)),
                ('run_id', models.CharField(blank=True, editable=False, max_length=36, null=True)),
                ('uuid', models.UUIDField(null=True, unique=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.childbot')),
            ],
        ),
        migrations.CreateModel(
            name='CommentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField()),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='core.comment')),
                ('tasks', models.ManyToManyField(to='core.Task')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tasks',
            field=models.ManyToManyField(to='core.Task'),
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('tasks', models.ManyToManyField(to='core.Task')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('username', 'service')},
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='core.profile')),
                ('tasks', models.ManyToManyField(to='core.Task')),
            ],
            options={
                'unique_together': {('profile', 'following')},
            },
        ),
    ]
