# Generated by Django 3.2 on 2025-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250317_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
