# Generated by Django 3.2 on 2025-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250317_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followings_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
