# Generated by Django 3.2 on 2025-01-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250119_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='info',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
