# Generated by Django 3.2 on 2025-01-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_location_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
