# Generated by Django 5.1.5 on 2025-03-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_id'),
    ]

    
