# Generated by Django 3.2 on 2025-01-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250119_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience')], max_length=50)),
                ('info', models.JSONField(blank=True, default={}, null=True)),
                ('rest_id', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('rest_id', 'service')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
    ]
