# Generated by Django 3.2 on 2025-01-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250119_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience')], default='instagram', max_length=50),
        ),
    ]
