# Generated by Django 3.2 on 2025-01-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_log_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='run_id',
            field=models.CharField(editable=False, max_length=36),
        ),
    ]
