# Generated by Django 3.2 on 2025-01-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_log_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='run_id',
            field=models.CharField(blank=True, editable=False, max_length=36, null=True),
        ),
    ]
