# Generated by Django 3.2 on 2025-04-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="The name of the data model (e.g., 'result', 'customer').", max_length=100)),
                ('object_id', models.CharField(db_index=True, help_text='The unique identifier of the object being locked.', max_length=255)),
                ('lock_type', models.CharField(choices=[('service', 'Service'), ('data_point', 'Data Point'), ('endpoint', 'Endpoint'), ('campaign_job', 'Campaign/Job')], db_index=True, help_text='The level at which the lock is acquired.', max_length=20)),
                ('locked_by_task', models.CharField(db_index=True, help_text='The ID of the task that holds the lock.', max_length=255)),
                ('lock_datetime', models.DateTimeField(auto_now_add=True, help_text='The date and time when the lock was acquired.')),
                ('associated_value', models.CharField(blank=True, db_index=True, help_text='An optional value associated with the lock type (e.g., service name, data point ID).', max_length=255, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='lock',
            index=models.Index(fields=['model_name', 'object_id', 'lock_type'], name='core_lock_model_n_8e73c7_idx'),
        ),
        migrations.AddIndex(
            model_name='lock',
            index=models.Index(fields=['locked_by_task'], name='core_lock_locked__4b2062_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lock',
            unique_together={('model_name', 'object_id', 'lock_type', 'associated_value')},
        ),
    ]
