# Generated by Django 3.2 on 2025-01-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_log_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bot_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
