# Generated by Django 3.2 on 2025-04-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20250404_2252'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lock',
            name='core_lock_locked__3fe7c7_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='data_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lock',
            name='locked_by_task',
            field=models.CharField(db_index=True, help_text='The ID of the task that holds the lock.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='lock',
            index=models.Index(fields=['locked_by_task'], name='core_lock_locked__4b2062_idx'),
        ),
    ]
