# Generated by Django 3.2 on 2025-01-20 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_log_bot_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.BigIntegerField()),
                ('request_record_type', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=255)),
                ('data_point', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('r_type', models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('put', 'PUT'), ('delete', 'DELETE')], max_length=10)),
                ('bot_username', models.CharField(blank=True, max_length=100)),
                ('logged_in', models.BooleanField(default=False)),
                ('params', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('data_text', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='core.task')),
            ],
        ),
    ]
