# Generated by Django 3.2 on 2025-01-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_requestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='datetime',
            field=models.DateField(),
        ),
    ]
