# Generated by Django 3.2 on 2025-04-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20250404_2257'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lock',
            name='core_lock_locked__4b2062_idx',
        ),
        migrations.AlterField(
            model_name='lock',
            name='locked_by_task',
            field=models.ForeignKey(help_text='The ID of the task that holds the lock.', on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AddIndex(
            model_name='lock',
            index=models.Index(fields=['locked_by_task'], name='core_lock_locked__3fe7c7_idx'),
        ),
    ]
