# Generated by Django 5.1.5 on 2025-04-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20250404_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='lock_type',
            field=models.CharField(choices=[('service', 'Service'), ('data_point', 'Data Point'), ('end_point', 'Endpoint'), ('campaign_job', 'Campaign/Job')], db_index=True, help_text='The level at which the lock is acquired.', max_length=20),
        ),
    ]
