# Generated by Django 3.2 on 2025-01-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_requestlog_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
