# Generated by Django 3.2 on 2025-01-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_requestlog_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='audience',
            name='Profiles',
        ),
        migrations.RemoveField(
            model_name='audience',
            name='campaigns',
        ),
        migrations.AddField(
            model_name='task',
            name='ref_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
