# Generated by Django 3.2 on 2025-01-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_server'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaign',
            new_name='BulkCampaign',
        ),
    ]
