# Generated by Django 3.2 on 2025-01-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_campaign_bulkcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
