# Generated by Django 3.2 on 2025-01-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_location_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='uuid',
        ),
        migrations.AddField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
