# Generated by Django 3.2 on 2025-02-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20250131_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', models.JSONField()),
                ('range_start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('range_end', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddField(
            model_name='output',
            name='block_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
